# Part A

Jacobi Method

In [1]:
import numpy as np
import time
def jacobi(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
        print(x)
    return x, max_iterations

In [2]:
# Example usage
A = np.array([[10, -1, 2, 0, 0],
              [-1, 11, -1, 3, 0],
              [2, -1, 10, -1, 0],
              [0, 3, -1, 8, -2],
              [0, 0, 0, -2, 9]])
b = np.array([14, 30, 26, 25, 37])
x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 100

start = time.perf_counter()

solution, iterations = jacobi(A, b, x0, tol, max_iterations)

end = time.perf_counter()
elapsed_time = end - start 

print(f"Solution: {solution}")
print(f"Iterations: {iterations}")
print(f"Time: {elapsed_time:.6e} seconds")

[1 2 2 3 4]
Solution: [1 2 2 3 4]
Iterations: 1
Time: 1.304221e-03 seconds


Gauss-Seidel Method

In [5]:
import numpy as np
def gauss_seidel(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    print(x)
    for k in range(max_iterations):
        x_new = x.copy()
        
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i)) # Using already updated values
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n)) # Using old values
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
        print(x)
    return x, max_iterations

In [6]:
# Example usage
A = np.array([[10, -1, 2, 0, 0],
              [-1, 11, -1, 3, 0],
              [2, -1, 10, -1, 0],
              [0, 3, -1, 8, -2],
              [0, 0, 0, -2, 9]])
b = np.array([14, 30, 26, 25, 37])
x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 100

start = time.perf_counter()

solution, iterations = gauss_seidel(A, b, x0, tol, max_iterations)

end = time.perf_counter()
elapsed_time = end - start

print(f"Solution: {solution}")
print(f"Iterations: {iterations}")
print(f"Time: {elapsed_time:.6e} seconds")

[0 0 0 0 0]
[1 2 2 2 4]
[1 2 2 3 4]
Solution: [1 2 2 3 4]
Iterations: 2
Time: 1.786099e-03 seconds


Convergence Comparison -Iteration: The Jacobi required fewer passes through the equations than the Jacobi method to reach the solution. -Decay: The size of the vectors in the Gauss-Seidel method decreased more rapidly than they did in the Jacobi method. -Time: The Jacobi method was slightly faster in reaching the solution than the Jacobi method was.

# Part B

Jacobi Method

In [7]:
import numpy as np
import time
def jacobi(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
        print(x)
    return x, max_iterations

In [8]:
# Example usage
A = np.array([[1, 2, 3, 0, 0],
              [2, 1, 2, 3, 0],
              [3, 2, 1, 2, 3],
              [0, 3, 2, 1, 2],
              [0, 0, 3, 2, 1]])
b = np.array([14, 22, 33, 26, 22])
x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 100

start = time.perf_counter()

solution, iterations = jacobi(A, b, x0, tol, max_iterations)

end = time.perf_counter()
elapsed_time = end - start 

print(f"Solution: {solution}")
print(f"Iterations: {iterations}")
print(f"Time: {elapsed_time:.6e} seconds")

[14 22 33 26 22]
[-129 -150 -171 -150 -129]
[ 827 1072 1407 1076  835]
[-6351 -7674 -9249 -7674 -6351]
[43109 54244 68835 54248 43117]
[-314979 -386610 -475629 -386610 -314979]
[2200121 2741068 3436347 2741072 2200129]
[-15791163 -19496130 -24164997 -19496130 -15791163]
[111487265 138400732 172731531 138400736 111487273]
[ -794996043  -983639778 -1222526517  -983639778  -794996043]
[5634859121 6985964476 8704535403 6985964480 5634859129]
[-40085535147 -49636682466 -61753012629 -49636682466 -40085535147]
[284532402833 352587142972 439059940779 352587142976 284532402841]
[-2022354108267 -2504946116130 -3117542988885 -2504946116130
 -2022354108267]
[14362521198929 17794632542716 22153909114155 17794632542720
 14362521198937]
[-102050992427883 -126416758254306 -157353657364437 -126416758254306
 -102050992427883]
[ 724894488601937  898059574347580 1117972987584555  898059574347584
  724894488601945]
[-5150038111448811 -6379913675415714 -7941605229001941 -6379913675415714
 -5150038111448811]

<ipython-input-7-0ca759080a7f>:9: RuntimeWarning: overflow encountered in long_scalars
  s = sum(A[i][j] * x[j] for j in range(n) if j != i)


Gauss-Seidel Method

In [9]:
import numpy as np
def gauss_seidel(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    print(x)
    for k in range(max_iterations):
        x_new = x.copy()
        
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i)) # Using already updated values
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n)) # Using old values
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
        print(x)
    return x, max_iterations

In [10]:
# Example usage
A = np.array([[1, 2, 3, 0, 0],
              [2, 1, 2, 3, 0],
              [3, 2, 1, 2, 3],
              [0, 3, 2, 1, 2],
              [0, 0, 3, 2, 1]])
b = np.array([14, 22, 33, 26, 22])
x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 100

start = time.perf_counter()

solution, iterations = jacobi(A, b, x0, tol, max_iterations)

end = time.perf_counter()
elapsed_time = end - start 

print(f"Solution: {solution}")
print(f"Iterations: {iterations}")
print(f"Time: {elapsed_time:.6e} seconds")

[14 22 33 26 22]
[-129 -150 -171 -150 -129]
[ 827 1072 1407 1076  835]
[-6351 -7674 -9249 -7674 -6351]
[43109 54244 68835 54248 43117]
[-314979 -386610 -475629 -386610 -314979]
[2200121 2741068 3436347 2741072 2200129]
[-15791163 -19496130 -24164997 -19496130 -15791163]
[111487265 138400732 172731531 138400736 111487273]
[ -794996043  -983639778 -1222526517  -983639778  -794996043]
[5634859121 6985964476 8704535403 6985964480 5634859129]
[-40085535147 -49636682466 -61753012629 -49636682466 -40085535147]
[284532402833 352587142972 439059940779 352587142976 284532402841]
[-2022354108267 -2504946116130 -3117542988885 -2504946116130
 -2022354108267]
[14362521198929 17794632542716 22153909114155 17794632542720
 14362521198937]
[-102050992427883 -126416758254306 -157353657364437 -126416758254306
 -102050992427883]
[ 724894488601937  898059574347580 1117972987584555  898059574347584
  724894488601945]
[-5150038111448811 -6379913675415714 -7941605229001941 -6379913675415714
 -5150038111448811]

<ipython-input-7-0ca759080a7f>:9: RuntimeWarning: overflow encountered in long_scalars
  s = sum(A[i][j] * x[j] for j in range(n) if j != i)


Convergence Comparison -Iteration: Both methods required all 100 iterations to reach a solution. -Decay: The size of the vectors decreased almost identically between the two methods. -Time: The Gauss-Seidel method reached a solution quicker than the Jacobi Method.