Linear Algebra

In [1]:
import numpy as np

In [2]:
v1 = np.array([1, 2, 3]) #3D vector
v2 = np.array([4, 5, 6])

In [3]:
print (v1)
print (v2)

[1 2 3]
[4 5 6]


In [6]:
v_add = v1 + v2
v_sub = v1 - v2

In [7]:
print (v_add)
print (v_sub)

[5 7 9]
[-3 -3 -3]


In [9]:
scalar = 2
v_scaled = scalar * v1

In [10]:
print (v_scaled)

[2 4 6]


In [11]:
dot_product = np.dot(v1, v2)

In [12]:
print (dot_product)

32


In [13]:
magnitude_v1 = np.linalg.norm(v1)
print (magnitude_v1)

3.7416573867739413


In [15]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
print()

B = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])
print(B)

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [16]:
C = np.array([[1, 2, 3], [4, 5, 6]])
matrix_add = A + C
matrix_sub = A - C

print("A+C=\n", matrix_add)
print("A-C=\n", matrix_sub)

A+C=
 [[ 2  4  6]
 [ 8 10 12]]
A-C=
 [[0 0 0]
 [0 0 0]]


In [17]:
matrix_mul = np.dot(A, B)

print(matrix_mul)

[[ 66  72  78]
 [156 171 186]]


In [18]:
transpose_A = A.T
print(transpose_A)

[[1 4]
 [2 5]
 [3 6]]


In [20]:
A = np.array([[2, 3], [4, -1]])
b = np.array([5, 3])
print(A)
print(b)

x = np.linalg.solve(A, b)
print ("Solution:")
print(x)

[[ 2  3]
 [ 4 -1]]
[5 3]
Solution:
[1. 1.]


In [23]:
A = np.array([[2, 1], [1, 2]])
e_value, e_vector = np.linalg.eig(A)
print ("eiganvalue:", e_value)
print("eiganvector:", e_vector)

eiganvalue: [3. 1.]
eiganvector: [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [24]:
A = np.array([[4, 7], [2, 6]])
A_inv = np.linalg.inv(A)

print(A)
print(A_inv)

[[4 7]
 [2 6]]
[[ 0.6 -0.7]
 [-0.2  0.4]]


In [25]:
identity = np.dot(A, A_inv)
print(identity)

[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


In [26]:
# Define a matrix
A = np.array([[1, 2], [3, 4], [5, 6]])

# Perform SVD
U, sigma, Vt = np.linalg.svd(A)

print("U matrix:\n", U)
print("Sigma values:", sigma)
print("V^T matrix:\n", Vt)

U matrix:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Sigma values: [9.52551809 0.51430058]
V^T matrix:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


Gaussian Elimination

In [30]:
import numpy as np
def gaussian_elimination(A, b):
    n = len(b)
    # Forward elimination
    for i in range(n):
        # Pivoting
        max_row = max(range(i, n), key=lambda x: abs(A[x][i]))
        A[i], A[max_row] = A[max_row], A[i]
        b[i], b[max_row] = b[max_row], b[i]

        # Make the rows below this one 0 in current column
        for j in range(i + 1, n):
            ratio = A[j][i] / A[i][i]
            A[j] = [A[j][k] - ratio * A[i][k] for k in range(n)]
            b[j] -= ratio * b[i]
    # Backward substitution
    x = [0] * n
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - sum(A[i][j] * x[j] for j in range(i + 1, n))) / A[i][i]
    return x

In [31]:
# Example Usage
A = [[3, 2, -4], [2, 3, 3], [5, -3, 1]]
b = [3, 15, 14]
solution = gaussian_elimination(A, b)
print(f"Solution: {solution}")

Solution: [2.9999999999999996, 0.9999999999999996, 2.0]


In [33]:
ans = np.linalg.solve(A,b)
print(ans)

[3. 1. 2.]


In [37]:
import numpy as np
def lu_decomposition(A):
    n = len(A)
    L = np.eye(n) # Initialize L as an identity matrix
    U = np.array(A, dtype=float) # Copy of A to avoid
    # modifying the original matrix
    
    # modifying the original matrix
    
    for i in range(n):
        # Eliminate elements below the pivot (U[i, i])
        for j in range(i+1, n):
            if U[i, i] == 0:
                raise ValueError("Zero pivot encountered. LU decomposition cannot proceed.")
                factor = U[j, i] / U[i, i] # Multiplier for row
                # operation
                L[j, i] = factor # Store multiplier in L
                # Update the rows of U
                for k in range(i, n):
                    U[j, k] -= factor * U[i, k]
    return L, U

In [38]:
# Example usage
A = np.array([[2, 3, 1],
[4, 7, -1],
[-2, 1, 2]])
L, U = lu_decomposition(A)
print("Matrix A:\n", A)
print("Lower Triangular Matrix L:\n", L)
print("Upper Triangular Matrix U:\n", U)

Matrix A:
 [[ 2  3  1]
 [ 4  7 -1]
 [-2  1  2]]
Lower Triangular Matrix L:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Upper Triangular Matrix U:
 [[ 2.  3.  1.]
 [ 4.  7. -1.]
 [-2.  1.  2.]]


In [40]:
print(np.matmul(L, U))
print(L@U)

[[ 2.  3.  1.]
 [ 4.  7. -1.]
 [-2.  1.  2.]]
[[ 2.  3.  1.]
 [ 4.  7. -1.]
 [-2.  1.  2.]]


In [41]:
from scipy.linalg import lu
A = np.array([])

Jacobi Method

In [42]:
import numpy as np
def jacobi(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
    return x, max_iterations

In [44]:
# Example usage
A = np.array([[4, -1, 0, 0],
              [-1, 4, -1, 0],
              [0, -1, 4, -1],
              [0, 0, -1, 3]])
b = np.array([15, 10, 10, 10])
x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 100
solution, iterations = jacobi(A, b, x0, tol, max_iterations)
print(f"Solution: {solution}")
print(f"Iterations: {iterations}")

Solution: [4 4 4 4]
Iterations: 3


Gauss-Seidel

In [45]:
import numpy as np
def gauss_seidel(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    print(x)
    for k in range(max_iterations):
        x_new = x.copy()
        
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i)) # Using already updated values
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n)) # Using old values
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
        print(x)
    return x, max_iterations

In [46]:
# Example usage
A = np.array([[4, -1, 0, 0],
              [-1, 4, -1, 0],
              [0, -1, 4, -1],
              [0, 0, -1, 3]])
b = np.array([15, 10, 10, 10])
x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 100
solution, iterations = gauss_seidel(A, b, x0, tol, max_iterations)
print(f"Solution: {solution}")
print(f"Iterations: {iterations}")

[0 0 0 0]
[3 3 3 4]
[4 4 4 4]
Solution: [4 4 4 4]
Iterations: 2


Determinants

In [47]:
import numpy as np
A = np.array([[2,1],[1,1]])
B = np.array([[2,4],[1,2]])
print(np.linalg.det(A))
print(np.linalg.det(B))

1.0
0.0


In [49]:
Ainv = np.linalg.inv(A)
#Binv = np.linalg.inv(B)

print(Ainv)
#print(Binv)

[[ 1. -1.]
 [-1.  2.]]


In [1]:
print ("A:")
print (f"A:{A}")

A:


NameError: name 'A' is not defined

Thomas Algorithm

In [4]:
import numpy as np
def thomas_algorithm(a, b, c, d):
    """
        Solve the tridiagonal system using the Thomas algorithm.
        a: sub-diagonal elements (length n-1)
    b: main diagonal elements (length n)
    c: super-diagonal elements (length n-1)
    d: right-hand side (length n)
    Returns: solution vector x of length n
    """
    n = len(b)
    # Forward elimination
    for i in range(1, n):
        w = a[i-1] / b[i-1]
        b[i] = b[i] - w * c[i-1]
        d[i] = d[i] - w * d[i-1]
    # Back substitution
    x = np.zeros(n)
    x[-1] = d[-1] / b[-1]
    for i in range(n-2, -1, -1):
        x[i] = (d[i] - c[i] * x[i+1]) / b[i]
    return x

# Example: solve a tridiagonal system
a = [1, 1, 1, 1] # Sub-diagonal (a_2, a_3, ..., a_n)
b = [4, 4, 4, 4, 4] # Main diagonal (b_1, b_2, ..., b_n)
c = [1, 1, 1, 1] # Super-diagonal (c_1, c_2, ..., c_{n-1})
d = [5, 6, 6, 6, 5] # Right-hand side (d_1, d_2, ..., d_n)
# Solve the system
x = thomas_algorithm(a, b, c, d)
print("Solution:", x)

Solution: [1. 1. 1. 1. 1.]
